### ISSUE TITLE
Release 0.2 -- Error on XFW-0053

### ISSUE THREAD

**Issue by paultravers** [wosk/flipperzero-tpms#11]
Tried to use the release 0.2 .fap on my flipper and received:

ERROR

Load failed RFID/tpms.fap
Update Application/Firmware to use this (MissingImports)

**Comment by Aholicknight** [comment]
Getting the same problem as well.

**Comment by wosk** [comment]
Probably XFW API version has been diverged with official.
You have to build by yourself.
