### ISSUE TITLE
What modulation does Schrader GG4 use?

### ISSUE THREAD

**Issue by Aholicknight** [wosk/flipperzero-tpms#12]
Hello. I am stuck on figuring out what to set the modulation  to receive a Schrader GG4 signal. It is currently set to AM650. Is this correct?

**Comment by wosk** [comment]
You have to choose modulation manually while receiving.

BTW. For each TPMS sensor there is a list of supported modulations:
https://github.com/wosk/flipperzero-tpms/blob/main/protocols/schrader_gg4.c#L100
