### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by ifuchs** [wosk/flipperzero-tpms#3]
I would like to try this app to see if I can read the TPMS on my Toyota Prius Prime. Can someone tell me (or point me to instructions) on building this app. (I didn't see it in any of the Custom FW.)

**Comment by wosk** [comment]
This app supports only Schrader GG4 at the moment.
To support TPMS sensors for Toyota Prius Prime you have to implement support for it by yourself. At least please provide an SDR record for analysis. It would be great if you know par tnumber/OEM/frequency/modulation.
You can also check if the rtl_433 tool on PC supports your sensors.

**Comment by ifuchs** [comment]
Yes, it is supported an RTL_ 433. Is there information I can give you from there that would help?

**Comment by ifuchs** [comment]
From the rtl_433 source: [tpms_toyota.txt](https://github.com/wosk/flipperzero-tpms/files/12548271/tpms_toyota.txt)

**Comment by joeashcraft** [comment]
> Can someone tell me (or point me to instructions) on building this app. (I didn't see it in any of the Custom FW.)

You might try the [flipc](https://flipc.org/wosk/flipperzero-tpms) tool, linked in this projects readme, to get this app to your flipperzero device. (it still won't read your Toyota TPMS yet)

**Comment by joeashcraft** [comment]
Maybe the maintainer can add a Github Action to compile the FAP for us and create a release here in this repo https://github.com/marketplace/actions/build-flipper-application-package-fap

**Comment by wosk** [comment]
[joeashcraft](https://github.com/joeashcraft)
You could download the recent version from flipc.org via button in Readme footer as well.
Release requires few clicks to do it, so flipc.org is more convenient to provide releases for my mind.

**Comment by wosk** [comment]
fresh fap could be downloaded from artifacts of latest run https://github.com/wosk/flipperzero-tpms/actions/workflows/build.yml
