### ISSUE TITLE
Preload failed

### ISSUE THREAD

**Issue by Hexen5588** [wosk/flipperzero-tpms#6]
Good morning,

I am very interested in your work because I have to use the relearn function of one of my valves on Citroen.

However, after loading the .fap file into /apps I get the following message:
Preload failed
TPMS/tpms-0.1.fap
Update application to use with this firmware (ApiTooOld).

What version of Flipper Zero firmware are you using?

Thx in advance,

**Comment by Ddubya454** [comment]
Same exact issue for me as well, knowing the firmware this last worked on would help.

**Comment by wosk** [comment]
It was compiled for recent version for the time of release.
Guys, use [UFBT](https://github.com/flipperdevices/flipperzero-ufbt) to compile for recent firmware by yourself.
Or use alternative firmware Unleashed, "e" pack should consist this fap.
