### ISSUE TITLE
Not compatible with firmware 0.100.3

### ISSUE THREAD

**Issue by nburkitt** [wosk/flipperzero-tpms#9]
Attempting to run on 0.100.3 gives this error:

![Screenshot_20240406-132029](https://github.com/wosk/flipperzero-tpms/assets/19785284/bc499e49-3921-4538-ab2f-7b0b9bf64914)

**Comment by nburkitt** [comment]
Sorry - forgot to mention that that's Release channel.

**Comment by wosk** [comment]
Please find out and try the latest release

**Comment by nburkitt** [comment]
Verified now working on 0.100.3. Спасибо!
